### ISSUE TITLE
SwiftUI-Audio

### ISSUE THREAD

**Issue by ganesh23here** [AgoraIO-Community/Agora-Audio-Example-iOS#4]
Hi Team,
We tried to run SwiftUI-Audio for passing RTM message. Updated RTM app ID and installed in two different devices, Entered channel name and user name. After clicking the Join Channel Button then it will change to Leave channel. But no members showing in both the device Member List.
Technically - self.channel?.join not called.

Any help on this to resolve>

Regards,
Ganesh

**Comment by maxxfrazer** [comment]
Sounds like an issue with the token possibly.
Follow the thread in this method to see what part fails:
https://github.com/AgoraIO-Community/Agora-Audio-Example-iOS/blob/3af3165148f922d50f434804d17e087729745c0d/SwiftUI-Example/SwiftUI-Audio/ContentView.swift#L94

Things to look for:
- Does the first if statement get skipped? The first time it should go into the if statement then check the `.login()` callback property rtmLoggedIn is of the correct value (`.ok`)
- If that's fine then do the same for `self.rtckit.joinChannel` called below

**Comment by ganesh23here** [comment]
Thanks @maxxfrazer 
Do we need to add RTM token in order to run? or Only AppID enough to run?

**Comment by ganesh23here** [comment]
@maxxfrazer AgoraObservable: AgoraRtmChannelDelegate, AgoraRtmDelegate for receiving RTM message not called. Can you help to address this?

**Comment by maxxfrazer** [comment]
@ganesh23here could you respond to my last 2 points to see if those methods are called?

**Comment by jstout2021** [comment]
I am having the same issue, I switched to my non M1 Mac to see if I can test this out. It hits the first statement and calls .login()
Gets to self.rtckit.joinChannel and then nothing.

**Comment by maxxfrazer** [comment]
I've gone ahead and tested this, seems to work for me (have attached a video showing simulator and physical device).

As mentioned in my first comment this is likely a result of passing a bad token. Please put a breakpoint inside the self.channel?.join callback, starting at line 107:
https://github.com/AgoraIO-Community/Agora-Audio-Example-iOS/blob/3af3165148f922d50f434804d17e087729745c0d/SwiftUI-Example/SwiftUI-Audio/ContentView.swift#L106


Alternatively you can create an App ID that does not require a token for development purposes. This project assumes you are not requiring a token, as explained in the blog which explains everything in the SwiftUI part of this repository:
https://www.agora.io/en/blog/creating-live-audio-chat-rooms-with-swiftui/

https://user-images.githubusercontent.com/5754073/127532911-461eea29-eb2d-4bd3-98dd-8d84ab6df880.mov

**Comment by jstout2021** [comment]
That is exactly what it was. Thank you very much for you time and helping with this... Now if only I could get it to work with my M1 :(

**Comment by jstout2021** [comment]
@maxxfrazer Just want to thank you again, I have a working example integrated with our app now. Everyone loves the sound quality. I am on the east coast my partner is on the west cost and it was better sounding than my ATT phone service! Thanks again for your efforts. I do need to get this M1 Mac issue worked out, I know its not the teams fault. For now I will just have to do with out the simulator and previews.

**Comment by maxxfrazer** [comment]
glad it’s working well for you now! ATT was my provider when I lived in the US and had pretty bad service in general 😅
are you able to provide any screenshots of the M1 issue? I’ve managed to get support added for the M1 simulator not long ago, so will chase about it depending on which framework isn’t working correctly.

**Comment by jstout2021** [comment]
I have honestly spent over 6 hours trying to solve this, all the setting the "Excluded Architectures" to arm64, Build Active Architecture Only to yes etc... It seems doing that I then get: Could not find module xxxxx for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator I have pretty much given up trying to solve it... I have just opened a new project, do my design stuff with swiftui there and then copy and paste it into my project... Twice I have screwed up the project so bad I could not recover it, had to re-dowload the branch I am working on... Been a real nightmare... 


<img width="1084" alt="Screen Shot 2021-07-30 at 02 29 43" src="https://user-images.githubusercontent.com/30294372/127617449-fec96096-6331-4391-8a3b-d614526be15f.png">

**Comment by maxxfrazer** [comment]
So the CocoaPods install does not work with the M1 Simulator at all, this has something to do with an issue distributing .xcframework files in CocoaPods.
I am confident that the framework listed there though (AgoraAudio_iOS) does work when either added directly or via Swift Package Manager. The other framework I'm unsure about at the moment is the RTM one, are there any error logs for that framework?

**Comment by jstout2021** [comment]
@maxxfrazer Just that error in the screen shot, I know that it started after I added this to my pod file. 
pod 'AgoraRtm_iOS', '~> 1.4'
pod 'AgoraAudio_iOS', '~> 3.2'

I ran the command pod install --repo--update like stated in the GitHub, that is when the error happens. If I comment them out and run pod install the error is gone and the simulator works fine. Here are all the pods I have installed:

pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'SDWebImageSwiftUI'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'AgoraRtm_iOS', '~> 1.4'
  pod 'AgoraAudio_iOS', '~> 3.2'

**Comment by maxxfrazer** [comment]
Sorry the strikeout in your last comment is a bit confusing, are the agora frameworks AgoraRtm_iOS and AgoraAudio_iOS or just the Audio one?
The audio SDK used there is quite old (Nov 2020), and at that time we didn't support the M1 simulator in any frameworks, M1 was still pretty new!
I think the best method would be adding the swift package for AgoraAudio_iOS from version 3.5. This can be done while keeping all your existing pods too - open up the project in Xcode and add the package there. So long as your installed CocoaPods version is from late last year (maybe even earlier) then it should be able to handle the fact you're using Pods and packages together.

**Comment by jstout2021** [comment]
@maxxfrazer not sure why the strikeout is there... in the file there is no strike out.

**Comment by jstout2021** [comment]
@maxxfrazer Still getting that same error / issue. Again tried the Excluding arm64, and other fixes available online.
<img width="1038" alt="Screen Shot 2021-07-30 at 09 50 33" src="https://user-images.githubusercontent.com/30294372/127671048-2b7c2171-dfab-4b6d-b3c3-ff782fa73a99.png">

**Comment by maxxfrazer** [comment]
Looks like you've added the swift package there, but still have the Pod for AgoraAudio_iOS. The package should replace it so remove it from your podfile and run pod install again.
However if you're still using Agora RTM (AgoraRtm_iOS) then the simulator will still not work, this is something the SDK team need to fix

**Comment by jstout2021** [comment]
@maxxfrazer Ok, thanks yeah I believe I need the AgoraRtm_iOS so ill just have to wait till they fix it. Its just my iMac so I can use my MacBook Pro to work on this. Thanks again for all your help.

**Comment by jstout2021** [comment]
@maxxfrazer I got this to work on my M1 with the simulator! I went into Projects -> Build Settings and added to Excluded Architectures Under Debug I added Any iOS Simulator SDK - arm64 did the same for Release, then I added this to my pod file :

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end

I ran pod install
Then cleaned the build folder
Then did a build and it was a success so I ran the project on the simulator and boom it worked!

**Comment by maxxfrazer** [comment]
Wow, glad rear worked for you then!

I’ve chased this and it should be working out the box on the next update

Closing this issue as the problem was about invalid tokens btw
