### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by jstout2021** [AgoraIO-Community/Agora-Audio-Example-iOS#5]
Followed the instructions, we are testing as we would love to use this service in our app... When I build for a device no problem... When I try to build for the simulator I get this error:
building for iOS Simulator, but linking in dylib built for iOS, file '/Users/xxxxxxx/Downloads/Agora-Audio-Example-iOS-main/SwiftUI-Example/Pods/AgoraAudio_iOS/AgoraAIDenoiseExtension.framework/AgoraAIDenoiseExtension' for architecture arm64

I have spent about 4 hours on this now trying to get this to work, kind of hard to test from just one device... 

I am using Xcode Version 12.5.1 (12E507) On an iMac (24-inch, M1, 2021) I have submitted a ticket, no answer, called support, no luck... support was only for sales they told me to submit a ticket... I am at a complete loss here...

**Comment by maxxfrazer** [comment]
Hi @jstout2021, there's an issue adding xcframeworks and the correct architectures to CocoaPods to then work on M1 Mac simulator devices unfortunately!

A simple solution that works for me is removing the CocoaPod dependency and instead adding the swift package:
https://github.com/AgoraIO/AgoraAudio_iOS

**Comment by jstout2021** [comment]
Did not work for me, gives other errors. The imports in this project will not work with the swift package... Nuts they would think that no one would use an M1 to develop with... They told me its recommended to be tested on a device... Ok fine... but it will render your preview mode useless with SwiftUI... so .... from this point on your app development can only be tested on a real device, no preview mode , no simulator...

**Comment by maxxfrazer** [comment]
The two options are using Swift Package Manager and manually installing the Agora frameworks. There is a lot of documentation on how to do these things, what are the errors you're getting when installing swift packages?

Are you correctly removing the CocoaPod dependencies?

**Comment by jstout2021** [comment]
I might not be, its their sample project... I have a client who wants his app done, I don't have time to spend another day searching google trying fixes to remove arm64, add this file, delete this file etc... Should not have to waste 2 days to load a sample project.... Its like I said before, not a good interdiction to the company... They should put in the first few lines, If your on a M1 Mac and don't care to loose the ability to use your preview or simulator than this is for you. Still going to need the same packages to add to my production app...

**Comment by maxxfrazer** [comment]
After spending a few minutes I deintegrated cocoapods and tried with swiftpm, it works fine.

I've added a commit to the branch [swiftpm-example](https://github.com/AgoraIO-Community/Agora-Audio-Example-iOS/tree/swiftpm-example) with this change.

Please take the time to review how to work with cocoapods etc, it will help in your iOS projects in the future.

**Comment by jstout2021** [comment]
Are. you serious , review how to work with CocoaPods... great response... Upgrade your code so issues like this dont happen... Do your research, you will see that thousands of people are having this issue with the M1 Macs... Maybe you should take the time to review how to update your frameworks.
